export const allRestaurantsTable = [
  {
    aggregatedDiscountInfoV3: {
      header: "₹100 OFF",
      subHeader: "ABOVE ₹499",
      discountTag: "FLAT DEAL",
    },
    areaName: "Electronic City",
    availability: {
      nextCloseTime: "2023-11-24 23:30:00",
      opened: true,
    },
    avgRating: 4.3,
    avgRatingString: "4.3",
    badges: true,
    cloudinaryImageId: "0030071ac2d8f8fb3ca435e4023e0fb7",
    costForTwo: "₹200 for two",
    cuisines: [
      "South Indian",
      "North Indian",
      "Chinese",
      "Chaat",
      "Desserts",
      "Tandoor",
    ],
    isOpen: true,
    name: "Sitara Veg",
    sla: {
      deliveryTime: 30,
      lastMileTravel: 6.9,
      serviceability: "SERVICEABLE",
      slaString: "30 mins",
      lastMileTravelString: "6.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "10K+",
    type: "F",
    veg: true,
  },
  {
    areaName: "Bellandur Sarjapur",
    availability: {
      nextCloseTime: "2023-11-24 23:00:00",
      opened: true,
    },
    avgRating: 4.6,
    avgRatingString: "4.6",
    badges: false,
    cloudinaryImageId: "27d43f8a2c1ca62704bb2dfd88d5b268",
    costForTwo: "₹250 for two",
    cuisines: ["Fast Food", "Snacks", "Indian", "Beverages"],
    isOpen: true,
    name: "Sandwich 2 Poha",
    sla: {
      deliveryTime: 33,
      lastMileTravel: 7.8,
      serviceability: "SERVICEABLE",
      slaString: "33 mins",
      lastMileTravelString: "7.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "100+",
    type: "F",
  },
  {
    areaName: "Sarjapur Road",
    availability: {
      nextCloseTime: "2023-11-24 22:30:00",
      opened: true,
    },
    avgRating: 4.4,
    avgRatingString: "4.4",
    badges: true,
    cloudinaryImageId: "t6c2esjgibs3nluwubvk",
    costForTwo: "₹600 for two",
    cuisines: [
      "Continental",
      "Indian",
      "Desserts",
      "Italian",
      "American",
      "Mediterranean",
      "Mexican",
      "Thai",
      "Asian",
      "Pan-Asian",
      "North Indian",
      "Home Food",
      "Healthy Food",
      "Snacks",
      "Pizzas",
      "Pastas",
      "Salads",
      "Beverages",
      "Bakery",
    ],
    isOpen: true,
    name: "The Nosh House",
    sla: {
      deliveryTime: 31,
      lastMileTravel: 5.7,
      serviceability: "SERVICEABLE",
      slaString: "31 mins",
      lastMileTravelString: "5.7 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "10K+",
    type: "C",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹120",
    },
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-12-01 00:00:00",
      opened: true,
    },
    avgRating: 4.2,
    avgRatingString: "4.2",
    badges: false,
    cloudinaryImageId: "bwkz4uv3qyx33brboywf",
    costForTwo: "₹100 for two",
    cuisines: ["Snacks", "Beverages", "Bakery", "Desserts", "Fast Food"],
    isOpen: true,
    name: " Irani Std. Tea",
    sla: {
      deliveryTime: 26,
      lastMileTravel: 3.9,
      serviceability: "SERVICEABLE",
      slaString: "26 mins",
      lastMileTravelString: "3.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "10% OFF",
      subHeader: "ABOVE ₹600",
      discountTag: "FLAT DEAL",
    },
    areaName: "Bommanahalli",
    availability: {
      nextCloseTime: "2023-11-25 00:00:00",
      opened: true,
    },
    avgRating: 4.1,
    avgRatingString: "4.1",
    badges: true,
    cloudinaryImageId: "bayh1ifkif253odm76x1",
    costForTwo: "₹399 for two",
    cuisines: ["Kerala", "South Indian", "Indian", "Chinese"],
    isOpen: true,
    name: "Adukkala - The Kerala Kitchen",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 3.5,
      serviceability: "SERVICEABLE",
      slaString: "25 mins",
      lastMileTravelString: "3.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    areaName: "Hsr Layout",
    availability: {
      nextCloseTime: "2023-11-25 07:00:00",
      opened: true,
    },
    avgRating: 4.1,
    avgRatingString: "4.1",
    badges: false,
    cloudinaryImageId: "tmfsttzf2uxtufett2gu",
    costForTwo: "₹150 for two",
    cuisines: ["American", "Beverages", "Juices", "Snacks"],
    isOpen: true,
    name: "Temperature",
    sla: {
      deliveryTime: 24,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "24 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "15% OFF",
      subHeader: "UPTO ₹45",
    },
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-11-24 23:00:00",
      opened: true,
    },
    avgRating: 4.2,
    avgRatingString: "4.2",
    badges: true,
    cloudinaryImageId: "t6vrkkgnnphonerbkqmu",
    costForTwo: "₹150 for two",
    cuisines: ["South Indian", "Ice Cream", "Beverages"],
    isOpen: true,
    name: "Davanagere Benne Dose Ruchi",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "25 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "500+",
    type: "F",
    veg: true,
  },
  {
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    areaName: "Kudlu Gate",
    availability: {
      nextCloseTime: "2023-11-24 23:00:00",
      opened: true,
    },
    avgRating: 4.1,
    avgRatingString: "4.1",
    badges: false,
    cloudinaryImageId: "8f0ff57e34acbded7099ba0207adb6c9",
    costForTwo: "₹250 for two",
    cuisines: ["North Indian", "Snacks", "Desserts"],
    isOpen: true,
    name: "Gopaljee Cafe",
    sla: {
      deliveryTime: 18,
      lastMileTravel: 1.3,
      serviceability: "SERVICEABLE",
      slaString: "18 mins",
      lastMileTravelString: "1.3 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "100+",
    type: "F",
    veg: true,
  },
  {
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
    areaName: "HSR",
    availability: {
      nextCloseTime: "2023-11-24 21:00:00",
      opened: true,
    },
    avgRating: 4,
    avgRatingString: "4.0",
    badges: true,
    cloudinaryImageId: "b39dbe0e90cd74c7af494d46bba888eb",
    costForTwo: "₹120 for two",
    cuisines: ["Snacks", "Fast Food"],
    isOpen: true,
    name: "Poha House",
    sla: {
      deliveryTime: 22,
      lastMileTravel: 1.6,
      serviceability: "SERVICEABLE",
      slaString: "22 mins",
      lastMileTravelString: "1.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "100+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
    areaName: "Kudlu Gate",
    availability: {
      nextCloseTime: "2023-11-24 22:30:00",
      opened: true,
    },
    avgRating: 4.2,
    avgRatingString: "4.2",
    badges: false,
    cloudinaryImageId: "b61937637b1066762d041c3f479e6ee6",
    costForTwo: "₹400 for two",
    cuisines: [
      "South Indian",
      "North Indian",
      "Chinese",
      "Chaat",
      "Beverages",
      "Juices",
      "Ice Cream",
      "Desserts",
    ],
    isOpen: true,
    name: "Sri Vishnu Leela Veg",
    sla: {
      deliveryTime: 18,
      lastMileTravel: 2,
      serviceability: "SERVICEABLE",
      slaString: "18 mins",
      lastMileTravelString: "2.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
    veg: true,
  },
  {
    areaName: "Electronic City",
    availability: {
      nextCloseTime: "2023-11-24 23:30:00",
      opened: true,
    },
    avgRating: 4.4,
    avgRatingString: "4.4",
    badges: true,
    cloudinaryImageId: "cd832b6167eb9f88aeb1ccdebf38d942",
    costForTwo: "₹350 for two",
    cuisines: ["American", "Beverages", "Continental", "Desserts", "Italian"],
    isOpen: true,
    name: "Truffles",
    sla: {
      deliveryTime: 30,
      lastMileTravel: 6,
      serviceability: "SERVICEABLE",
      slaString: "30 mins",
      lastMileTravelString: "6.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "10K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    areaName: "Singasandra",
    availability: {
      nextCloseTime: "2023-11-24 23:59:00",
      opened: true,
    },
    avgRating: 4.2,
    avgRatingString: "4.2",
    badges: false,
    cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
    costForTwo: "₹500 for two",
    cuisines: [
      "Kebabs",
      "Fast Food",
      "Snacks",
      "North Indian",
      "American",
      "Healthy Food",
      "Desserts",
      "Beverages",
    ],
    isOpen: true,
    name: "Faasos - Wraps & Rolls",
    sla: {
      deliveryTime: 29,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "29 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "ITEMS",
      subHeader: "AT ₹169",
    },
    areaName: "Singasandra",
    availability: {
      nextCloseTime: "2023-11-24 23:59:00",
      opened: true,
    },
    avgRating: 4.2,
    avgRatingString: "4.2",
    badges: true,
    cloudinaryImageId: "4edcfc66d91018d69894941ebb3c8d16",
    costForTwo: "₹300 for two",
    cuisines: [
      "Biryani",
      "North Indian",
      "Punjabi",
      "Healthy Food",
      "Desserts",
      "Beverages",
    ],
    isOpen: true,
    name: "LunchBox - Meals and Thalis",
    sla: {
      deliveryTime: 23,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "23 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "₹100 OFF",
      subHeader: "ABOVE ₹699",
      discountTag: "FLAT DEAL",
    },
    areaName: "Aecs Layout",
    availability: {
      nextCloseTime: "2023-11-24 23:59:00",
      opened: true,
    },
    avgRating: 4,
    avgRatingString: "4.0",
    badges: false,
    cloudinaryImageId: "nhuh3xfmqhqhmytonsux",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    isOpen: true,
    name: "Domino's Pizza",
    sla: {
      deliveryTime: 25,
      serviceability: "SERVICEABLE",
      slaString: "25 mins",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "500+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "10% OFF",
      subHeader: "UPTO ₹40",
    },
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-11-24 22:45:00",
      opened: true,
    },
    avgRating: 4,
    avgRatingString: "4.0",
    badges: true,
    cloudinaryImageId: "yhbw3q7cpqcdulli3m8c",
    costForTwo: "₹300 for two",
    cuisines: ["Maharashtrian", "Fast Food", "North Indian", "Beverages"],
    isOpen: true,
    name: "Mast Marathi",
    sla: {
      deliveryTime: 28,
      lastMileTravel: 3.6,
      serviceability: "SERVICEABLE",
      slaString: "28 mins",
      lastMileTravelString: "3.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "5K+",
    type: "F",
    veg: true,
  },
  {
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-11-25 01:00:00",
      opened: true,
    },
    avgRating: 4.5,
    avgRatingString: "4.5",
    badges: false,
    cloudinaryImageId: "d96267738c19ec62acb5390e52faba41",
    costForTwo: "₹400 for two",
    cuisines: ["Beverages", "Bakery", "Continental"],
    isOpen: true,
    name: "Third Wave Coffee",
    sla: {
      deliveryTime: 24,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "24 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    areaName: "Bommanahalli",
    availability: {
      nextCloseTime: "2023-11-25 00:00:00",
      opened: true,
    },
    avgRating: 4.1,
    avgRatingString: "4.1",
    badges: true,
    cloudinaryImageId: "xyabtge77bltvbdzzpqw",
    costForTwo: "₹250 for two",
    cuisines: ["Kerala", "Biryani", "South Indian", "Chinese"],
    isOpen: true,
    name: "Nandanam Restaurant",
    sla: {
      deliveryTime: 26,
      lastMileTravel: 3.5,
      serviceability: "SERVICEABLE",
      slaString: "26 mins",
      lastMileTravelString: "3.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-11-24 22:45:00",
      opened: true,
    },
    avgRating: 4,
    avgRatingString: "4.0",
    badges: false,
    cloudinaryImageId: "35af35bbe264c75d355c8e68959d1dcc",
    costForTwo: "₹300 for two",
    cuisines: ["Kerala", "Biryani", "Seafood", "South Indian"],
    isOpen: true,
    name: "Kumarakom",
    sla: {
      deliveryTime: 28,
      lastMileTravel: 3.6,
      serviceability: "SERVICEABLE",
      slaString: "28 mins",
      lastMileTravelString: "3.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "10K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
    areaName: "Bommanahalli",
    availability: {
      nextCloseTime: "2023-11-24 23:00:00",
      opened: true,
    },
    avgRating: 3.9,
    avgRatingString: "3.9",
    badges: true,
    cloudinaryImageId: "6dcc0253613f704d1a2ef76dd2a3615a",
    costForTwo: "₹400 for two",
    cuisines: ["Snacks", "Indian", "Beverages"],
    isOpen: true,
    name: "Between The Bread",
    sla: {
      deliveryTime: 34,
      lastMileTravel: 3.8,
      serviceability: "SERVICEABLE",
      slaString: "34 mins",
      lastMileTravelString: "3.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
    areaName: "Bommanahalli",
    availability: {
      nextCloseTime: "2023-11-24 23:00:00",
      opened: true,
    },
    avgRating: 3.9,
    avgRatingString: "3.9",
    badges: false,
    cloudinaryImageId: "a06715b3035935ddbf5d0a3a57900857",
    costForTwo: "₹300 for two",
    cuisines: ["Snacks", "Beverages"],
    isOpen: true,
    name: "Uncle Peter's Pancakes",
    sla: {
      deliveryTime: 31,
      lastMileTravel: 3.8,
      serviceability: "SERVICEABLE",
      slaString: "31 mins",
      lastMileTravelString: "3.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    areaName: "Kudlu Gate",
    availability: {
      nextCloseTime: "2023-11-24 15:00:00",
      opened: true,
    },
    avgRating: 4.2,
    avgRatingString: "4.2",
    badges: true,
    cloudinaryImageId: "a2c090bfa2b350174e3062a8201f6daf",
    costForTwo: "₹200 for two",
    cuisines: ["North Indian", "Chaat", "Beverages"],
    isOpen: true,
    name: "Bhartiya Jalpan",
    sla: {
      deliveryTime: 24,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "24 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "500+",
    type: "F",
    veg: true,
  },
  {
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-11-24 23:59:00",
      opened: true,
    },
    avgRating: 4.4,
    avgRatingString: "4.4",
    badges: false,
    cloudinaryImageId: "d43174beec6460f7db06b147ef8d438c",
    costForTwo: "₹800 for two",
    cuisines: ["Bakery", "Desserts", "Beverages", "Continental", "Italian"],
    isOpen: true,
    name: "Glen's Bakehouse",
    sla: {
      deliveryTime: 26,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "26 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "₹125 OFF",
      subHeader: "ABOVE ₹249",
      discountTag: "FLAT DEAL",
    },
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-11-24 22:45:00",
      opened: true,
    },
    avgRating: 4.2,
    avgRatingString: "4.2",
    badges: true,
    cloudinaryImageId: "hk39cgljd1cor1cynmpu",
    costForTwo: "₹99 for two",
    cuisines: ["Snacks", "Beverages"],
    isOpen: true,
    name: "Sandwich Guru",
    sla: {
      deliveryTime: 19,
      lastMileTravel: 2.9,
      serviceability: "SERVICEABLE",
      slaString: "19 mins",
      lastMileTravelString: "2.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "10K+",
    type: "F",
    veg: true,
  },
  {
    areaName: "HSR Sector 1",
    availability: {
      nextCloseTime: "2023-11-24 23:00:00",
      opened: true,
    },
    avgRating: 4.3,
    avgRatingString: "4.3",
    badges: false,
    cloudinaryImageId: "d6608954945e3221cc95ce0efa1dc581",
    costForTwo: "₹600 for two",
    cuisines: ["Cafe", "Healthy Food", "Beverages", "Desserts", "American"],
    isOpen: true,
    name: "Blue Tokai Coffee Roasters",
    sla: {
      deliveryTime: 26,
      lastMileTravel: 3.8,
      serviceability: "SERVICEABLE",
      slaString: "26 mins",
      lastMileTravelString: "3.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "500+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
    },
    areaName: "Sarjapur Road",
    availability: {
      nextCloseTime: "2023-11-24 23:59:00",
      opened: true,
    },
    avgRating: 4,
    avgRatingString: "4.0",
    badges: true,
    cloudinaryImageId: "fbkihhbpn9dpcirfea2w",
    costForTwo: "₹300 for two",
    cuisines: ["Biryani", "Mughlai", "North Indian"],
    isOpen: true,
    name: "Thalassery Restaurant",
    sla: {
      deliveryTime: 28,
      lastMileTravel: 4.6,
      serviceability: "SERVICEABLE",
      slaString: "28 mins",
      lastMileTravelString: "4.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "10K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "60% OFF",
      subHeader: "UPTO ₹120",
    },
    areaName: "Bommanahalli",
    availability: {
      nextCloseTime: "2023-11-25 02:00:00",
      opened: true,
    },
    avgRating: 4.1,
    avgRatingString: "4.1",
    badges: false,
    cloudinaryImageId: "nkgmotigo3crhistijm4",
    costForTwo: "₹250 for two",
    cuisines: ["Kerala", "Seafood", "Biryani", "South Indian"],
    isOpen: true,
    name: "Tharavadu family restaurant",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 3.7,
      serviceability: "SERVICEABLE",
      slaString: "25 mins",
      lastMileTravelString: "3.7 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "10K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "30% OFF",
      subHeader: "UPTO ₹75",
    },
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-11-24 21:45:00",
      opened: true,
    },
    avgRating: 4.1,
    avgRatingString: "4.1",
    badges: true,
    cloudinaryImageId: "cfuy40sao5rn3hgfjkok",
    costForTwo: "₹150 for two",
    cuisines: ["South Indian", "Beverages", "Chinese"],
    isOpen: true,
    name: "MDP Coffee House",
    sla: {
      deliveryTime: 23,
      lastMileTravel: 3.6,
      serviceability: "SERVICEABLE",
      slaString: "23 mins",
      lastMileTravelString: "3.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
    veg: true,
  },
  {
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
    },
    areaName: "Electronic City",
    availability: {
      nextCloseTime: "2023-11-24 22:00:00",
      opened: true,
    },
    avgRating: 4.3,
    avgRatingString: "4.3",
    badges: false,
    cloudinaryImageId: "0984acc0ed7b914206dbbcb90297becc",
    costForTwo: "₹300 for two",
    cuisines: [
      "Tibetan",
      "Healthy Food",
      "Asian",
      "Chinese",
      "Snacks",
      "Continental",
      "Desserts",
      "Beverages",
    ],
    isOpen: true,
    name: "Wow! Momo",
    sla: {
      deliveryTime: 28,
      lastMileTravel: 3.8,
      serviceability: "SERVICEABLE",
      slaString: "28 mins",
      lastMileTravelString: "3.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    areaName: "HSR Layout",
    availability: {
      nextCloseTime: "2023-11-25 02:00:00",
      opened: true,
    },
    avgRating: 3.8,
    avgRatingString: "3.8",
    badges: true,
    cloudinaryImageId: "umocqqvl4q3jxchqalfz",
    costForTwo: "₹400 for two",
    cuisines: ["Biryani", "Kebabs", "North Indian", "Hyderabadi"],
    isOpen: true,
    name: "Paradise Biryani",
    sla: {
      deliveryTime: 24,
      lastMileTravel: 3.9,
      serviceability: "SERVICEABLE",
      slaString: "24 mins",
      lastMileTravelString: "3.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "10K+",
    type: "F",
  },
  {
    aggregatedDiscountInfoV3: {
      header: "₹125 OFF",
      subHeader: "ABOVE ₹199",
      discountTag: "FLAT DEAL",
    },
    areaName: "Bommanahalli",
    availability: {
      nextCloseTime: "2023-11-24 22:15:00",
      opened: true,
    },
    avgRating: 4.2,
    avgRatingString: "4.2",
    badges: false,
    cloudinaryImageId: "pdkvqzq3hn28cvzfsnos",
    costForTwo: "₹200 for two",
    cuisines: ["South Indian", "North Indian", "Chinese"],
    isOpen: true,
    name: "Udupi Upahar",
    sla: {
      deliveryTime: 20,
      lastMileTravel: 1.5,
      serviceability: "SERVICEABLE",
      slaString: "20 mins",
      lastMileTravelString: "1.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    totalRatingsString: "1K+",
    type: "F",
    veg: true,
  },
];
