const topRestaurantsTable = [
  {
    name: "McDonald's",
    cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
    locality: "HRBR Layout",
    areaName: "Kammanahalli/Kalyan Nagar",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
    avgRating: 4.2,
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
  },
  {
    name: "Domino's Pizza",
    cloudinaryImageId: "rt65grdkdrsxwdlecvvv",
    locality: "Kacharakanahalli",
    areaName: "Hennur",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4,
    avgRatingString: "4.0",
    totalRatingsString: "10K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "₹100 OFF",
      subHeader: "ABOVE ₹999",
      discountTag: "FLAT DEAL",
    },
  },
  {
    name: "KFC",
    cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
    locality: "Kalyan Nagar",
    areaName: "Kalyan Nagar",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    avgRating: 4.1,
    avgRatingString: "4.1",
    totalRatingsString: "10K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
  },
  {
    name: "Chaayos Chai+Snacks=Relax",
    cloudinaryImageId: "cace805a6ba74137571d0f7ac92302b1",
    locality: "Kacharakanahalli",
    areaName: "Kammanahalli",
    costForTwo: "₹250 for two",
    cuisines: [
      "Bakery",
      "Beverages",
      "Chaat",
      "Desserts",
      "Home Food",
      "Italian",
      "Maharashtrian",
      "Snacks",
      "Street Food",
      "Sweets",
    ],
    avgRating: 4.4,
    avgRatingString: "4.4",
    totalRatingsString: "5K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "60% OFF",
      subHeader: "UPTO ₹120",
    },
  },
  {
    name: "Theobroma",
    cloudinaryImageId: "b033728dcb0101ceb19bff0e1e1f6474",
    locality: "2nd Block - Hrbr Layout",
    areaName: "Kalyan Nagar",
    costForTwo: "₹800 for two",
    cuisines: ["Bakery", "Desserts"],
    avgRating: 4.5,
    avgRatingString: "4.5",
    totalRatingsString: "1K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "10% OFF",
      subHeader: "ABOVE ₹159",
      discountTag: "FLAT DEAL",
    },
  },
  {
    name: "Leon's - Burgers & Wings (Leon Grill)",
    cloudinaryImageId: "s0ld89fix521kcrm6rpm",
    locality: "HRBR Layout",
    areaName: "Kalyan Nagar",
    costForTwo: "₹300 for two",
    cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
    avgRating: 4.3,
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
  },
  {
    name: "Subway",
    cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
    locality: "HRBR Layout",
    areaName: "Kalyan Nagar",
    costForTwo: "₹350 for two",
    cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 3.8,
    avgRatingString: "3.8",
    totalRatingsString: "10K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
  },
  {
    name: "A2B - Adyar Ananda Bhavan",
    cloudinaryImageId: "cqprnl8jjt5wr0fqxcip",
    locality: "2nd Block - Hrbr Layout",
    areaName: "Kalyan Nagar",
    costForTwo: "₹300 for two",
    cuisines: ["South Indian", "North Indian", "Sweets", "Chinese"],
    avgRating: 4.3,
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
  },
  {
    name: "Faasos - Wraps & Rolls",
    cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
    locality: "HRBR Layout 3rd Block",
    areaName: "Kamanahalli",
    costForTwo: "₹200 for two",
    cuisines: [
      "Kebabs",
      "Fast Food",
      "Snacks",
      "North Indian",
      "American",
      "Healthy Food",
      "Desserts",
      "Beverages",
    ],
    avgRating: 4.1,
    avgRatingString: "4.1",
    totalRatingsString: "10K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "60% OFF",
      subHeader: "UPTO ₹120",
    },
  },
  {
    name: "Pizza Hut",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    locality: "Kalyan Nagar",
    areaName: "Kalyan Nagar",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: 3.8,
    avgRatingString: "3.8",
    totalRatingsString: "10K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
    },
  },
  {
    name: "CakeZone",
    cloudinaryImageId: "2857960242f8d1d4d390dc22a38c530e",
    locality: "1ST STAGE",
    areaName: "Hennur Bellary Road Layout",
    costForTwo: "₹200 for two",
    cuisines: ["Bakery", "Desserts", "Sweets", "Ice Cream"],
    avgRating: 4.3,
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "60% OFF",
      subHeader: "UPTO ₹120",
    },
  },
  {
    name: "Chai Point",
    cloudinaryImageId: "cnlhkx4qw7vcrasx8the",
    locality: "2nd Block - Hrbr Layout",
    areaName: "Kalyan Nagar",
    costForTwo: "₹150 for two",
    cuisines: [
      "Bakery",
      "Beverages",
      "Maharashtrian",
      "Snacks",
      "Street Food",
      "South Indian",
      "Punjabi",
      "Chaat",
      "Indian",
      "American",
      "North Indian",
      "Fast Food",
      "Desserts",
      "Cafe",
      "Healthy Food",
      "Home Food",
    ],
    avgRating: 4.3,
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "60% OFF",
      subHeader: "UPTO ₹120",
    },
  },
  {
    name: "Starbucks Coffee",
    cloudinaryImageId: "2418209798927d733a50f5d2ebcc2aee",
    locality: "2nd block",
    areaName: "Kalyan Nagar",
    costForTwo: "₹400 for two",
    cuisines: [
      "Beverages",
      "Cafe",
      "Snacks",
      "Desserts",
      "Bakery",
      "Ice Cream",
    ],
    avgRating: 4.3,
    avgRatingString: "4.3",
    totalRatingsString: "1K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
    },
  },
  {
    name: "Kanti Sweets",
    cloudinaryImageId: "geqgsr7huonqac9umcm9",
    locality: "Ramaiah Layout",
    areaName: "Kammanahalli",
    costForTwo: "₹150 for two",
    cuisines: ["Sweets"],
    avgRating: 4.5,
    avgRatingString: "4.5",
    totalRatingsString: "5K+",
    badges: false,
    aggregatedDiscountInfoV3: {},
  },
  {
    name: "Baskin Robbins - Ice Cream Desserts",
    cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
    locality: "2nd Block - HBR Layout",
    areaName: "HBR Layout",
    costForTwo: "₹250 for two",
    cuisines: ["Desserts"],
    avgRating: 4.6,
    avgRatingString: "4.6",
    totalRatingsString: "1K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
  },
  {
    name: "California Burrito",
    cloudinaryImageId: "beggcu7941kviqihro2y",
    locality: "Hennur Main Road",
    areaName: "Kalyan Nagar",
    costForTwo: "₹250 for two",
    cuisines: [
      "Mexican",
      "American",
      "Salads",
      "Continental",
      "Keto",
      "Healthy Food",
    ],
    avgRating: 4.5,
    avgRatingString: "4.5",
    totalRatingsString: "10K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
  },
  {
    name: "EatFit",
    cloudinaryImageId: "6126c9b45de2cb222405c1af8a321e74",
    locality: "Dodda Banaswadi Main Rd",
    areaName: "Hennur",
    costForTwo: "₹270 for two",
    cuisines: [
      "Chinese",
      "Healthy Food",
      "Tandoor",
      "Pizzas",
      "North Indian",
      "Thalis",
      "Biryani",
    ],
    avgRating: 4.2,
    avgRatingString: "4.2",
    totalRatingsString: "5K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "₹125 OFF",
      subHeader: "ABOVE ₹249",
      discountTag: "FLAT DEAL",
    },
  },
  {
    name: "Nandhana Palace",
    cloudinaryImageId: "195876a3181ef63f76e45e3a7b49b585",
    locality: "Kammanahalli",
    areaName: "Kammanahalli",
    costForTwo: "₹500 for two",
    cuisines: ["Biryani", "Andhra", "South Indian", "North Indian"],
    avgRating: 4.2,
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "10% OFF",
      subHeader: "ABOVE ₹900",
      discountTag: "FLAT DEAL",
    },
  },
  {
    name: "The Good Bowl",
    cloudinaryImageId: "6e04be27387483a7c00444f8e8241108",
    locality: "HRBR Layout 3rd Block",
    areaName: "Kamanahalli",
    costForTwo: "₹400 for two",
    cuisines: [
      "Biryani",
      "North Indian",
      "Pastas",
      "Punjabi",
      "Desserts",
      "Beverages",
    ],
    avgRating: 3.9,
    avgRatingString: "3.9",
    totalRatingsString: "1K+",
    badges: true,
    aggregatedDiscountInfoV3: {
      header: "60% OFF",
      subHeader: "UPTO ₹120",
    },
  },
  {
    name: "Apsara Ice Creams",
    cloudinaryImageId: "xh73g63oxtw1ucce8jwl",
    locality: "HRBR Layout",
    areaName: "Kalyan Nagar",
    costForTwo: "₹150 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.6,
    avgRatingString: "4.6",
    totalRatingsString: "1K+",
    badges: false,
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
    },
  },
];

export { topRestaurantsTable };
